name: Supabase DB Backup

on:
  workflow_dispatch:        # 手動觸發
  schedule:
    - cron: '0 21 * * *'    # 每天 05:00 台灣時間（UTC+8）→ 21:00 UTC

permissions:
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest
    # 如果你的 DATABASE_URL 放在某個 Environment（例如 "production"），就打開下一行：
    # environment: production

    steps:
      - name: Install pg_dump (postgresql-client)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check secrets and show versions
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          if [ -z "${DATABASE_URL:-}" ]; then
            echo "❌ DATABASE_URL secret is missing or empty."
            echo "請到 GitHub → Settings → Secrets and variables → Actions 設定 DATABASE_URL。"
            exit 1
          fi
          echo "::add-mask::${DATABASE_URL}"
          echo "✅ DATABASE_URL is present."
          psql --version
          pg_dump --version

      - name: Connectivity test (psql)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          # 一定要包含 sslmode=require，且用 Direct 連線 (5432)
          # 會印出時間，確認連得上
          psql "$DATABASE_URL" -tAc "select now();"

      - name: Dump database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y%m%d-%H%M%S')"
          mkdir -p backups
          # 使用 custom 格式（.dump）較適合還原/壓縮
          pg_dump --dbname="$DATABASE_URL" \
                  --no-owner \
                  --format=custom \
                  --file="backups/supabase-${TS}.dump"
          ls -lh backups

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backups/*.dump
          retention-days: 7

      - name: Connectivity test (psql)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          # 一定要包含 sslmode=require，且用 Direct 連線 (5432)
          # 會印出時間，確認連得上
          psql "$DATABASE_URL" -tAc "select now();"

      - name: Dump database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y%m%d-%H%M%S')"
          mkdir -p backups
          # 使用 custom 格式（.dump）較適合還原/壓縮
          pg_dump --dbname="$DATABASE_URL" \
                  --no-owner \
                  --format=custom \
                  --file="backups/supabase-${TS}.dump"
          ls -lh backups

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backups/*.dump
          retention-days: 7
